version: "3.5"
services:
  postgres:
    image: "postgres:latest"
    container_name: postgres
    ports:
      - "13000:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: test
    networks:
      - mynetwork
  service:
    build: .
    container_name: service
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - mynetwork

networks:
  mynetwork: