definitions:
  delivery.CreateEntryIn:
    properties:
      name:
        type: string
      project_id:
        type: integer
      time_end:
        type: string
      time_start:
        type: string
    required:
    - project_id
    - time_end
    - time_start
    type: object
  delivery.CreateEntryOut:
    properties:
      id:
        type: integer
    required:
    - id
    type: object
  delivery.EntryOut:
    properties:
      id:
        type: integer
      name:
        type: string
      project_id:
        type: integer
      time_end:
        type: string
      time_start:
        type: string
    type: object
  echo.HTTPError:
    properties:
      message: {}
    type: object
info:
  contact: {}
paths:
  /entries/create:
    post:
      consumes:
      - application/json
      description: Create entry.
      parameters:
      - description: entry info
        in: body
        name: entry
        required: true
        schema:
          $ref: '#/definitions/delivery.CreateEntryIn'
      produces:
      - application/json
      responses:
        "200":
          description: success create entry
          schema:
            $ref: '#/definitions/delivery.CreateEntryOut'
        "400":
          description: bad request
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "404":
          description: item is not found
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "422":
          description: unprocessable entity
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/echo.HTTPError'
      summary: Create entry.
      tags:
      - entries
  /me/entries:
    get:
      consumes:
      - application/json
      description: Get my entries or get my entries for a day
      parameters:
      - description: day for events in YYYY-MM-DD format
        in: query
        name: day
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success create entry
          schema:
            items:
              $ref: '#/definitions/delivery.EntryOut'
            type: array
        "400":
          description: bad request
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/echo.HTTPError'
      summary: Get my entries.
      tags:
      - entries
swagger: "2.0"
