definitions:
  echo.HTTPError:
    properties:
      message: {}
    type: object
  github.com_BMSTU-TIMETRACKERS_timetracker-backend_internal_entry_delivery.CreateEntryIn:
    properties:
      name:
        type: string
      project_id:
        type: integer
      time_end:
        type: string
      time_start:
        type: string
    required:
    - project_id
    - time_end
    - time_start
    type: object
  github.com_BMSTU-TIMETRACKERS_timetracker-backend_internal_entry_delivery.CreateEntryOut:
    properties:
      id:
        type: integer
    required:
    - id
    type: object
  github.com_BMSTU-TIMETRACKERS_timetracker-backend_internal_entry_delivery.EntryOut:
    properties:
      id:
        type: integer
      name:
        type: string
      project_id:
        type: integer
      project_name:
        type: string
      time_end:
        type: string
      time_start:
        type: string
    type: object
  github.com_BMSTU-TIMETRACKERS_timetracker-backend_internal_goal_delivery.CreateGoalIn:
    properties:
      date_end:
        type: string
      date_start:
        type: string
      name:
        type: string
      project_id:
        type: integer
      time_seconds:
        type: integer
    required:
    - date_end
    - date_start
    - name
    - project_id
    - time_seconds
    type: object
  github.com_BMSTU-TIMETRACKERS_timetracker-backend_internal_goal_delivery.CreateGoalOut:
    properties:
      id:
        type: integer
    required:
    - id
    type: object
  github.com_BMSTU-TIMETRACKERS_timetracker-backend_internal_goal_delivery.GoalOut:
    properties:
      date_end:
        type: string
      date_start:
        type: string
      duration_seconds:
        type: number
      id:
        type: integer
      name:
        type: string
      percent:
        type: number
      project_id:
        type: integer
      time_seconds:
        type: integer
      user_id:
        type: integer
    type: object
  github.com_BMSTU-TIMETRACKERS_timetracker-backend_internal_project_delivery.CreateProjectIn:
    properties:
      name:
        type: string
    required:
    - name
    type: object
  github.com_BMSTU-TIMETRACKERS_timetracker-backend_internal_project_delivery.CreateProjectOut:
    properties:
      id:
        type: integer
    required:
    - id
    type: object
  github.com_BMSTU-TIMETRACKERS_timetracker-backend_internal_project_delivery.ProjectEntriesStat:
    properties:
      duration_in_sec:
        type: number
      name:
        type: string
      percent_duration:
        type: number
    type: object
  github.com_BMSTU-TIMETRACKERS_timetracker-backend_internal_project_delivery.ProjectEntriesStatOut:
    properties:
      entries:
        items:
          $ref: '#/definitions/github.com_BMSTU-TIMETRACKERS_timetracker-backend_internal_project_delivery.ProjectEntriesStat'
        type: array
      total_duration_in_sec:
        type: number
    type: object
  github.com_BMSTU-TIMETRACKERS_timetracker-backend_internal_project_delivery.ProjectOut:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  github.com_BMSTU-TIMETRACKERS_timetracker-backend_internal_project_delivery.ProjectStat:
    properties:
      duration_in_sec:
        type: number
      id:
        type: integer
      name:
        type: string
      percent_duration:
        type: number
    type: object
  github.com_BMSTU-TIMETRACKERS_timetracker-backend_internal_project_delivery.ProjectsStatOut:
    properties:
      projects:
        items:
          $ref: '#/definitions/github.com_BMSTU-TIMETRACKERS_timetracker-backend_internal_project_delivery.ProjectStat'
        type: array
      total_duration_in_sec:
        type: number
    type: object
  internal_entry_delivery.CreateEntryIn:
    properties:
      name:
        type: string
      project_id:
        type: integer
      time_end:
        type: string
      time_start:
        type: string
    required:
    - project_id
    - time_end
    - time_start
    type: object
  internal_entry_delivery.CreateEntryOut:
    properties:
      id:
        type: integer
    required:
    - id
    type: object
  internal_entry_delivery.EntryOut:
    properties:
      id:
        type: integer
      name:
        type: string
      project_id:
        type: integer
      project_name:
        type: string
      time_end:
        type: string
      time_start:
        type: string
    type: object
  internal_goal_delivery.CreateGoalIn:
    properties:
      date_end:
        type: string
      date_start:
        type: string
      name:
        type: string
      project_id:
        type: integer
      time_seconds:
        type: integer
    required:
    - date_end
    - date_start
    - name
    - project_id
    - time_seconds
    type: object
  internal_goal_delivery.CreateGoalOut:
    properties:
      id:
        type: integer
    required:
    - id
    type: object
  internal_goal_delivery.GoalOut:
    properties:
      date_end:
        type: string
      date_start:
        type: string
      duration_seconds:
        type: number
      id:
        type: integer
      name:
        type: string
      percent:
        type: number
      project_id:
        type: integer
      time_seconds:
        type: integer
      user_id:
        type: integer
    type: object
  internal_project_delivery.CreateProjectIn:
    properties:
      name:
        type: string
    required:
    - name
    type: object
  internal_project_delivery.CreateProjectOut:
    properties:
      id:
        type: integer
    required:
    - id
    type: object
  internal_project_delivery.ProjectEntriesStat:
    properties:
      duration_in_sec:
        type: number
      name:
        type: string
      percent_duration:
        type: number
    type: object
  internal_project_delivery.ProjectEntriesStatOut:
    properties:
      entries:
        items:
          $ref: '#/definitions/internal_project_delivery.ProjectEntriesStat'
        type: array
      total_duration_in_sec:
        type: number
    type: object
  internal_project_delivery.ProjectOut:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  internal_project_delivery.ProjectStat:
    properties:
      duration_in_sec:
        type: number
      id:
        type: integer
      name:
        type: string
      percent_duration:
        type: number
    type: object
  internal_project_delivery.ProjectsStatOut:
    properties:
      projects:
        items:
          $ref: '#/definitions/internal_project_delivery.ProjectStat'
        type: array
      total_duration_in_sec:
        type: number
    type: object
info:
  contact: {}
paths:
  /entries/create:
    post:
      consumes:
      - application/json
      description: Create entry.
      parameters:
      - description: entry info
        in: body
        name: entry
        required: true
        schema:
          $ref: '#/definitions/internal_entry_delivery.CreateEntryIn'
      produces:
      - application/json
      responses:
        "200":
          description: success create entry
          schema:
            $ref: '#/definitions/internal_entry_delivery.CreateEntryOut'
        "400":
          description: bad request
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "404":
          description: item is not found
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "422":
          description: unprocessable entity
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/echo.HTTPError'
      summary: Create entry.
      tags:
      - entries
  /goals/create:
    post:
      consumes:
      - application/json
      description: Create goal.
      parameters:
      - description: goal info
        in: body
        name: goal
        required: true
        schema:
          $ref: '#/definitions/internal_goal_delivery.CreateGoalIn'
      produces:
      - application/json
      responses:
        "200":
          description: success create goal
          schema:
            $ref: '#/definitions/internal_goal_delivery.CreateGoalOut'
        "400":
          description: bad request
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "404":
          description: item is not found
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "422":
          description: unprocessable entity
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/echo.HTTPError'
      summary: Create goal.
      tags:
      - goals
  /me/entries:
    get:
      consumes:
      - application/json
      description: Get my entries or get my entries for a day
      parameters:
      - description: day for events in YYYY-MM-DD format
        in: query
        name: day
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success create entry
          schema:
            items:
              $ref: '#/definitions/internal_entry_delivery.EntryOut'
            type: array
        "400":
          description: bad request
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/echo.HTTPError'
      summary: Get my entries.
      tags:
      - entries
  /me/projects:
    get:
      consumes:
      - application/json
      description: Get my projects or get my projects for a day
      produces:
      - application/json
      responses:
        "200":
          description: success get projects
          schema:
            items:
              $ref: '#/definitions/github.com_BMSTU-TIMETRACKERS_timetracker-backend_internal_project_delivery.ProjectOut'
            type: array
        "400":
          description: bad request
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/echo.HTTPError'
      summary: Get my projects.
      tags:
      - projects
  /me/projects/{id}/stat:
    get:
      consumes:
      - application/json
      description: Get project entries stat
      parameters:
      - description: project ID
        in: path
        name: id
        required: true
        type: integer
      - description: RFC3339 format
        in: query
        name: time_start
        type: string
      - description: RFC3339 format
        in: query
        name: time_end
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/github.com_BMSTU-TIMETRACKERS_timetracker-backend_internal_project_delivery.ProjectEntriesStatOut'
        "400":
          description: bad request
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/echo.HTTPError'
      summary: Get project entries stat.
      tags:
      - projects
  /me/projects/{project_id}/goals:
    get:
      consumes:
      - application/json
      description: Get my goals for project
      parameters:
      - description: project id
        in: path
        name: project_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: success get goals
          schema:
            items:
              $ref: '#/definitions/internal_goal_delivery.GoalOut'
            type: array
        "400":
          description: bad request
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/echo.HTTPError'
      summary: Get my goals for project.
      tags:
      - goals
  /me/projects/stat:
    get:
      consumes:
      - application/json
      description: Get project stats
      parameters:
      - description: RFC3339 format
        in: query
        name: time_start
        type: string
      - description: RFC3339 format
        in: query
        name: time_end
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/github.com_BMSTU-TIMETRACKERS_timetracker-backend_internal_project_delivery.ProjectsStatOut'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/echo.HTTPError'
      summary: Get project stats.
      tags:
      - projects
  /projects/create:
    post:
      consumes:
      - application/json
      description: Create project.
      parameters:
      - description: project info
        in: body
        name: project
        required: true
        schema:
          $ref: '#/definitions/github.com_BMSTU-TIMETRACKERS_timetracker-backend_internal_project_delivery.CreateProjectIn'
      produces:
      - application/json
      responses:
        "200":
          description: success create project
          schema:
            $ref: '#/definitions/github.com_BMSTU-TIMETRACKERS_timetracker-backend_internal_project_delivery.CreateProjectOut'
        "400":
          description: bad request
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "422":
          description: unprocessable entity
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/echo.HTTPError'
      summary: Create project.
      tags:
      - projects
swagger: "2.0"
