definitions:
  echo.HTTPError:
    properties:
      message: {}
    type: object
  internal_entry_delivery.CreateEntryIn:
    properties:
      name:
        type: string
      project_id:
        type: integer
      time_end:
        type: string
      time_start:
        type: string
    required:
    - project_id
    - time_end
    - time_start
    type: object
  internal_entry_delivery.CreateEntryOut:
    properties:
      id:
        type: integer
    required:
    - id
    type: object
  internal_entry_delivery.EntryOut:
    properties:
      id:
        type: integer
      name:
        type: string
      project_id:
        type: integer
      project_name:
        type: string
      time_end:
        type: string
      time_start:
        type: string
    type: object
  internal_project_delivery.CreateProjectIn:
    properties:
      name:
        type: string
    required:
    - name
    type: object
  internal_project_delivery.CreateProjectOut:
    properties:
      id:
        type: integer
    required:
    - id
    type: object
  internal_project_delivery.ProjectOut:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  internal_project_delivery.ProjectStat:
    properties:
      duration_in_hours:
        type: number
      id:
        type: integer
      name:
        type: string
      percent_duration:
        type: number
    type: object
  internal_project_delivery.ProjectsStatOut:
    properties:
      projects:
        items:
          $ref: '#/definitions/internal_project_delivery.ProjectStat'
        type: array
      total_duration_in_hours:
        type: number
    type: object
info:
  contact: {}
paths:
  /entries/create:
    post:
      consumes:
      - application/json
      description: Create entry.
      parameters:
      - description: entry info
        in: body
        name: entry
        required: true
        schema:
          $ref: '#/definitions/internal_entry_delivery.CreateEntryIn'
      produces:
      - application/json
      responses:
        "200":
          description: success create entry
          schema:
            $ref: '#/definitions/internal_entry_delivery.CreateEntryOut'
        "400":
          description: bad request
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "404":
          description: item is not found
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "422":
          description: unprocessable entity
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/echo.HTTPError'
      summary: Create entry.
      tags:
      - entries
  /me/entries:
    get:
      consumes:
      - application/json
      description: Get my entries or get my entries for a day
      parameters:
      - description: day for events in YYYY-MM-DD format
        in: query
        name: day
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success create entry
          schema:
            items:
              $ref: '#/definitions/internal_entry_delivery.EntryOut'
            type: array
        "400":
          description: bad request
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/echo.HTTPError'
      summary: Get my entries.
      tags:
      - entries
  /me/projects:
    get:
      consumes:
      - application/json
      description: Get my projects or get my projects for a day
      produces:
      - application/json
      responses:
        "200":
          description: success get projects
          schema:
            items:
              $ref: '#/definitions/internal_project_delivery.ProjectOut'
            type: array
        "400":
          description: bad request
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/echo.HTTPError'
      summary: Get my projects.
      tags:
      - projects
  /me/projects/stat:
    get:
      consumes:
      - application/json
      description: Get project stats
      parameters:
      - description: RFC3339 format
        in: query
        name: time_start
        type: string
      - description: RFC3339 format
        in: query
        name: time_end
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/internal_project_delivery.ProjectsStatOut'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/echo.HTTPError'
      summary: Get project stats.
      tags:
      - projects
  /projects/create:
    post:
      consumes:
      - application/json
      description: Create project.
      parameters:
      - description: project info
        in: body
        name: project
        required: true
        schema:
          $ref: '#/definitions/internal_project_delivery.CreateProjectIn'
      produces:
      - application/json
      responses:
        "200":
          description: success create project
          schema:
            $ref: '#/definitions/internal_project_delivery.CreateProjectOut'
        "400":
          description: bad request
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "422":
          description: unprocessable entity
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/echo.HTTPError'
      summary: Create project.
      tags:
      - projects
swagger: "2.0"
